{% set name = "auroris" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/auroris-{{ version }}.tar.gz
  sha256: 4159b6f0afca275cda55d3b1d8853e3f4020e314972e0d77b5640bd4620a7b8d

build:
  entry_points:
    - auroris = auroris.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.10
    - pip
    - tqdm
    - loguru
    - typer
    - pydantic >=2
    - numpy
    - pandas <2.2.0
    - scipy
    - scikit-learn
    - seaborn
    - datamol >=0.12.1
    - pillow
    - fsspec

test:
  imports:
    - auroris
  commands:
    - pip check
    - auroris --help
  requires:
    - pip

about:
  summary: Tools for data curation in the Polaris ecosystem.
  license: Apache-2.0
  license_file: LICENSE
  home: https://github.com/polaris-hub/auroris

extra:
  recipe-maintainers:
    - cwognum
    - zhu0619
